### ISSUE TITLE
More TODO

### ISSUE THREAD

**Issue by jrogerthat** [visdesignlab/trrracer#12]
- [x] error on flatMap when you create a thread
- [x] make the highlighted text just around the word
- [x] reset time button
- [x] bread crumb vis shows where you hopped in detail view (this ties the ephemeral concept jumping with the 
- [x] prev/next arrows in detail view by activity name in detail view (in topbar)
- [x] create 'Add Tag' button to activity tags in detail view
- [x] need to require a file type when you add a file!!!
- [x] Page exploration - PDF? HTML? Iframe? Div? Need to decide how this will be structured to best tag
- [x] Add query search as more of a popover on the right sidebar
- [x] Prompt artifact type on file add
- [x] Integrate the RT view with the overview
- [x] add marker to image?
- [x] add refs to PDF
- [x] run script from James
- [x] fix react pdf css
- [x] add events to bubble view
- [x] fix not tag update
- [ ] glyphs for swarm plot?
- [x] Desktop to HTML version
- [x] Page exploration - tagging parts of text for RT's
- [ ] Tag grouping functionality
- [ ] Integrate detail view with the overview?
- [x] fix tooltip logic
- [ ] clear query bar when you exit out of query view

**Comment by jrogerthat** [comment]
- [ ] add refs to PDF
- [ ] run script from James
- [ ] fix react pdf css
- [ ] add events to bubble view
- [ ] reset time button
- [ ] fix not tag update

**Comment by jrogerthat** [comment]
- [ ] Desktop to HTML version
- [ ] Page exploration - tagging parts of text for RT's
- [ ] Page exploration - PDF? HTML? Iframe? Div? Need to decide how this will be structured to best tag
- [ ] Tag grouping functionality
- [ ] Prompt artifact type on file add
- [x] Integrate the RT view with the overview
- [ ] Integrate detail view with the overview?
- [x] Add query search as more of a popover on the right sidebar
- [ ] fix tooltip logic
